# Generated by Django 5.1.3 on 2024-12-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='terms_and_condition',
            field=models.BooleanField(default=False),
        ),
    ]
